// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.10.0
// source: generate_operate.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//获取运营活动列表
type OperateGetListC2S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OperateGetListC2S) Reset() {
	*x = OperateGetListC2S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generate_operate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateGetListC2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateGetListC2S) ProtoMessage() {}

func (x *OperateGetListC2S) ProtoReflect() protoreflect.Message {
	mi := &file_generate_operate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateGetListC2S.ProtoReflect.Descriptor instead.
func (*OperateGetListC2S) Descriptor() ([]byte, []int) {
	return file_generate_operate_proto_rawDescGZIP(), []int{0}
}

//获取运营活动列表
type OperateGetListS2C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Operate `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"` //活动详细信息
}

func (x *OperateGetListS2C) Reset() {
	*x = OperateGetListS2C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generate_operate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateGetListS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateGetListS2C) ProtoMessage() {}

func (x *OperateGetListS2C) ProtoReflect() protoreflect.Message {
	mi := &file_generate_operate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateGetListS2C.ProtoReflect.Descriptor instead.
func (*OperateGetListS2C) Descriptor() ([]byte, []int) {
	return file_generate_operate_proto_rawDescGZIP(), []int{1}
}

func (x *OperateGetListS2C) GetList() []*Operate {
	if x != nil {
		return x.List
	}
	return nil
}

//添加运营活动
type OperateNewS2C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Operate `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"` //活动详细信息
}

func (x *OperateNewS2C) Reset() {
	*x = OperateNewS2C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generate_operate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateNewS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateNewS2C) ProtoMessage() {}

func (x *OperateNewS2C) ProtoReflect() protoreflect.Message {
	mi := &file_generate_operate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateNewS2C.ProtoReflect.Descriptor instead.
func (*OperateNewS2C) Descriptor() ([]byte, []int) {
	return file_generate_operate_proto_rawDescGZIP(), []int{2}
}

func (x *OperateNewS2C) GetList() []*Operate {
	if x != nil {
		return x.List
	}
	return nil
}

//更新运营活动内容
type OperateUpdateS2C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Detailed []*OperateActivityDB `protobuf:"bytes,1,rep,name=detailed,proto3" json:"detailed,omitempty"` //更新内容
}

func (x *OperateUpdateS2C) Reset() {
	*x = OperateUpdateS2C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generate_operate_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateUpdateS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateUpdateS2C) ProtoMessage() {}

func (x *OperateUpdateS2C) ProtoReflect() protoreflect.Message {
	mi := &file_generate_operate_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateUpdateS2C.ProtoReflect.Descriptor instead.
func (*OperateUpdateS2C) Descriptor() ([]byte, []int) {
	return file_generate_operate_proto_rawDescGZIP(), []int{3}
}

func (x *OperateUpdateS2C) GetDetailed() []*OperateActivityDB {
	if x != nil {
		return x.Detailed
	}
	return nil
}

//删除运营活动
type OperateDeleteS2C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId int64 `protobuf:"varint,1,opt,name=activityId,proto3" json:"activityId,omitempty"` //活动Id
}

func (x *OperateDeleteS2C) Reset() {
	*x = OperateDeleteS2C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generate_operate_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateDeleteS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateDeleteS2C) ProtoMessage() {}

func (x *OperateDeleteS2C) ProtoReflect() protoreflect.Message {
	mi := &file_generate_operate_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateDeleteS2C.ProtoReflect.Descriptor instead.
func (*OperateDeleteS2C) Descriptor() ([]byte, []int) {
	return file_generate_operate_proto_rawDescGZIP(), []int{4}
}

func (x *OperateDeleteS2C) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

//领取运营任务奖励
type OperateGetTaskRewardC2S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId int64   `protobuf:"varint,1,opt,name=activityId,proto3" json:"activityId,omitempty"`  // 活动Id
	TplIndex   int32   `protobuf:"varint,2,opt,name=tplIndex,proto3" json:"tplIndex,omitempty"`      // 模板索引
	TaskIds    []int32 `protobuf:"varint,3,rep,packed,name=taskIds,proto3" json:"taskIds,omitempty"` //条目id
}

func (x *OperateGetTaskRewardC2S) Reset() {
	*x = OperateGetTaskRewardC2S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generate_operate_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateGetTaskRewardC2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateGetTaskRewardC2S) ProtoMessage() {}

func (x *OperateGetTaskRewardC2S) ProtoReflect() protoreflect.Message {
	mi := &file_generate_operate_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateGetTaskRewardC2S.ProtoReflect.Descriptor instead.
func (*OperateGetTaskRewardC2S) Descriptor() ([]byte, []int) {
	return file_generate_operate_proto_rawDescGZIP(), []int{5}
}

func (x *OperateGetTaskRewardC2S) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *OperateGetTaskRewardC2S) GetTplIndex() int32 {
	if x != nil {
		return x.TplIndex
	}
	return 0
}

func (x *OperateGetTaskRewardC2S) GetTaskIds() []int32 {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

//领取运营任务奖励
type OperateGetTaskRewardS2C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId int64   `protobuf:"varint,1,opt,name=activityId,proto3" json:"activityId,omitempty"`  // 活动Id
	TplIndex   int32   `protobuf:"varint,2,opt,name=tplIndex,proto3" json:"tplIndex,omitempty"`      // 模板索引
	TaskIds    []int32 `protobuf:"varint,3,rep,packed,name=taskIds,proto3" json:"taskIds,omitempty"` //条目id
}

func (x *OperateGetTaskRewardS2C) Reset() {
	*x = OperateGetTaskRewardS2C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generate_operate_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateGetTaskRewardS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateGetTaskRewardS2C) ProtoMessage() {}

func (x *OperateGetTaskRewardS2C) ProtoReflect() protoreflect.Message {
	mi := &file_generate_operate_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateGetTaskRewardS2C.ProtoReflect.Descriptor instead.
func (*OperateGetTaskRewardS2C) Descriptor() ([]byte, []int) {
	return file_generate_operate_proto_rawDescGZIP(), []int{6}
}

func (x *OperateGetTaskRewardS2C) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *OperateGetTaskRewardS2C) GetTplIndex() int32 {
	if x != nil {
		return x.TplIndex
	}
	return 0
}

func (x *OperateGetTaskRewardS2C) GetTaskIds() []int32 {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

//签到
type OperateSignC2S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId int64 `protobuf:"varint,1,opt,name=activityId,proto3" json:"activityId,omitempty"` // 活动Id
	TplIndex   int32 `protobuf:"varint,2,opt,name=tplIndex,proto3" json:"tplIndex,omitempty"`     // 模板索引
}

func (x *OperateSignC2S) Reset() {
	*x = OperateSignC2S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generate_operate_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateSignC2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateSignC2S) ProtoMessage() {}

func (x *OperateSignC2S) ProtoReflect() protoreflect.Message {
	mi := &file_generate_operate_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateSignC2S.ProtoReflect.Descriptor instead.
func (*OperateSignC2S) Descriptor() ([]byte, []int) {
	return file_generate_operate_proto_rawDescGZIP(), []int{7}
}

func (x *OperateSignC2S) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *OperateSignC2S) GetTplIndex() int32 {
	if x != nil {
		return x.TplIndex
	}
	return 0
}

//签到
type OperateSignS2C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId int64 `protobuf:"varint,1,opt,name=activityId,proto3" json:"activityId,omitempty"` // 活动Id
	TplIndex   int32 `protobuf:"varint,2,opt,name=tplIndex,proto3" json:"tplIndex,omitempty"`     // 模板索引
}

func (x *OperateSignS2C) Reset() {
	*x = OperateSignS2C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generate_operate_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateSignS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateSignS2C) ProtoMessage() {}

func (x *OperateSignS2C) ProtoReflect() protoreflect.Message {
	mi := &file_generate_operate_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateSignS2C.ProtoReflect.Descriptor instead.
func (*OperateSignS2C) Descriptor() ([]byte, []int) {
	return file_generate_operate_proto_rawDescGZIP(), []int{8}
}

func (x *OperateSignS2C) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *OperateSignS2C) GetTplIndex() int32 {
	if x != nil {
		return x.TplIndex
	}
	return 0
}

//补签
type OperateRepairSignC2S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId int64 `protobuf:"varint,1,opt,name=activityId,proto3" json:"activityId,omitempty"` // 活动Id
	TplIndex   int32 `protobuf:"varint,2,opt,name=tplIndex,proto3" json:"tplIndex,omitempty"`     // 模板索引
}

func (x *OperateRepairSignC2S) Reset() {
	*x = OperateRepairSignC2S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generate_operate_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateRepairSignC2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateRepairSignC2S) ProtoMessage() {}

func (x *OperateRepairSignC2S) ProtoReflect() protoreflect.Message {
	mi := &file_generate_operate_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateRepairSignC2S.ProtoReflect.Descriptor instead.
func (*OperateRepairSignC2S) Descriptor() ([]byte, []int) {
	return file_generate_operate_proto_rawDescGZIP(), []int{9}
}

func (x *OperateRepairSignC2S) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *OperateRepairSignC2S) GetTplIndex() int32 {
	if x != nil {
		return x.TplIndex
	}
	return 0
}

//补签
type OperateRepairSignS2C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId int64 `protobuf:"varint,1,opt,name=activityId,proto3" json:"activityId,omitempty"` // 活动Id
	TplIndex   int32 `protobuf:"varint,2,opt,name=tplIndex,proto3" json:"tplIndex,omitempty"`     // 模板索引
}

func (x *OperateRepairSignS2C) Reset() {
	*x = OperateRepairSignS2C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generate_operate_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateRepairSignS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateRepairSignS2C) ProtoMessage() {}

func (x *OperateRepairSignS2C) ProtoReflect() protoreflect.Message {
	mi := &file_generate_operate_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateRepairSignS2C.ProtoReflect.Descriptor instead.
func (*OperateRepairSignS2C) Descriptor() ([]byte, []int) {
	return file_generate_operate_proto_rawDescGZIP(), []int{10}
}

func (x *OperateRepairSignS2C) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *OperateRepairSignS2C) GetTplIndex() int32 {
	if x != nil {
		return x.TplIndex
	}
	return 0
}

//购买商品
type OperateShopBuyC2S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId int64 `protobuf:"varint,1,opt,name=activityId,proto3" json:"activityId,omitempty"` // 活动Id
	TplIndex   int32 `protobuf:"varint,2,opt,name=tplIndex,proto3" json:"tplIndex,omitempty"`     // 模板索引
	GoodsIndex int32 `protobuf:"varint,3,opt,name=goodsIndex,proto3" json:"goodsIndex,omitempty"` // 商品索引
}

func (x *OperateShopBuyC2S) Reset() {
	*x = OperateShopBuyC2S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generate_operate_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateShopBuyC2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateShopBuyC2S) ProtoMessage() {}

func (x *OperateShopBuyC2S) ProtoReflect() protoreflect.Message {
	mi := &file_generate_operate_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateShopBuyC2S.ProtoReflect.Descriptor instead.
func (*OperateShopBuyC2S) Descriptor() ([]byte, []int) {
	return file_generate_operate_proto_rawDescGZIP(), []int{11}
}

func (x *OperateShopBuyC2S) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *OperateShopBuyC2S) GetTplIndex() int32 {
	if x != nil {
		return x.TplIndex
	}
	return 0
}

func (x *OperateShopBuyC2S) GetGoodsIndex() int32 {
	if x != nil {
		return x.GoodsIndex
	}
	return 0
}

//购买商品
type OperateShopBuyS2C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId int64 `protobuf:"varint,1,opt,name=activityId,proto3" json:"activityId,omitempty"` // 活动Id
	TplIndex   int32 `protobuf:"varint,2,opt,name=tplIndex,proto3" json:"tplIndex,omitempty"`     // 模板索引
	GoodsIndex int32 `protobuf:"varint,3,opt,name=goodsIndex,proto3" json:"goodsIndex,omitempty"` // 商品索引
}

func (x *OperateShopBuyS2C) Reset() {
	*x = OperateShopBuyS2C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generate_operate_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateShopBuyS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateShopBuyS2C) ProtoMessage() {}

func (x *OperateShopBuyS2C) ProtoReflect() protoreflect.Message {
	mi := &file_generate_operate_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateShopBuyS2C.ProtoReflect.Descriptor instead.
func (*OperateShopBuyS2C) Descriptor() ([]byte, []int) {
	return file_generate_operate_proto_rawDescGZIP(), []int{12}
}

func (x *OperateShopBuyS2C) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *OperateShopBuyS2C) GetTplIndex() int32 {
	if x != nil {
		return x.TplIndex
	}
	return 0
}

func (x *OperateShopBuyS2C) GetGoodsIndex() int32 {
	if x != nil {
		return x.GoodsIndex
	}
	return 0
}

//获取积分奖励
type OperateGetScoreRewardC2S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId int64 `protobuf:"varint,1,opt,name=activityId,proto3" json:"activityId,omitempty"` // 活动Id
	ScoreIndex int32 `protobuf:"varint,2,opt,name=scoreIndex,proto3" json:"scoreIndex,omitempty"` // 积分索引
}

func (x *OperateGetScoreRewardC2S) Reset() {
	*x = OperateGetScoreRewardC2S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generate_operate_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateGetScoreRewardC2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateGetScoreRewardC2S) ProtoMessage() {}

func (x *OperateGetScoreRewardC2S) ProtoReflect() protoreflect.Message {
	mi := &file_generate_operate_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateGetScoreRewardC2S.ProtoReflect.Descriptor instead.
func (*OperateGetScoreRewardC2S) Descriptor() ([]byte, []int) {
	return file_generate_operate_proto_rawDescGZIP(), []int{13}
}

func (x *OperateGetScoreRewardC2S) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *OperateGetScoreRewardC2S) GetScoreIndex() int32 {
	if x != nil {
		return x.ScoreIndex
	}
	return 0
}

//获取积分奖励
type OperateGetScoreRewardS2C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId int64 `protobuf:"varint,1,opt,name=activityId,proto3" json:"activityId,omitempty"` // 活动Id
	ScoreIndex int32 `protobuf:"varint,2,opt,name=scoreIndex,proto3" json:"scoreIndex,omitempty"` // 积分索引
}

func (x *OperateGetScoreRewardS2C) Reset() {
	*x = OperateGetScoreRewardS2C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generate_operate_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateGetScoreRewardS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateGetScoreRewardS2C) ProtoMessage() {}

func (x *OperateGetScoreRewardS2C) ProtoReflect() protoreflect.Message {
	mi := &file_generate_operate_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateGetScoreRewardS2C.ProtoReflect.Descriptor instead.
func (*OperateGetScoreRewardS2C) Descriptor() ([]byte, []int) {
	return file_generate_operate_proto_rawDescGZIP(), []int{14}
}

func (x *OperateGetScoreRewardS2C) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *OperateGetScoreRewardS2C) GetScoreIndex() int32 {
	if x != nil {
		return x.ScoreIndex
	}
	return 0
}

var File_generate_operate_proto protoreflect.FileDescriptor

var file_generate_operate_proto_rawDesc = []byte{
	0x0a, 0x16, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x47, 0x61, 0x6d, 0x65, 0x1a, 0x1d,
	0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x13, 0x0a,
	0x11, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x43,
	0x32, 0x53, 0x22, 0x36, 0x0a, 0x11, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x47, 0x65, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x53, 0x32, 0x43, 0x12, 0x21, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x2e, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x32, 0x0a, 0x0d, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x53, 0x32, 0x43, 0x12, 0x21, 0x0a, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x47, 0x61, 0x6d, 0x65,
	0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x47,
	0x0a, 0x10, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x32, 0x43, 0x12, 0x33, 0x0a, 0x08, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x2e, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x44, 0x42, 0x52, 0x08, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x22, 0x32, 0x0a, 0x10, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x32, 0x43, 0x12, 0x1e, 0x0a, 0x0a, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x22, 0x6f, 0x0a, 0x17, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x43, 0x32, 0x53, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x70, 0x6c, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x70, 0x6c, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x73, 0x22, 0x6f, 0x0a, 0x17,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x53, 0x32, 0x43, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x70, 0x6c, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x70, 0x6c, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x73, 0x22, 0x4c, 0x0a,
	0x0e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x43, 0x32, 0x53, 0x12,
	0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x74, 0x70, 0x6c, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x74, 0x70, 0x6c, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x4c, 0x0a, 0x0e, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x53, 0x32, 0x43, 0x12, 0x1e, 0x0a,
	0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x74, 0x70, 0x6c, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x74, 0x70, 0x6c, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x52, 0x0a, 0x14, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x61, 0x69, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x43, 0x32,
	0x53, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x70, 0x6c, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x70, 0x6c, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x52, 0x0a,
	0x14, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x61, 0x69, 0x72, 0x53, 0x69,
	0x67, 0x6e, 0x53, 0x32, 0x43, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x70, 0x6c, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x70, 0x6c, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x22, 0x6f, 0x0a, 0x11, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x70,
	0x42, 0x75, 0x79, 0x43, 0x32, 0x53, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x70, 0x6c, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x70, 0x6c, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x22, 0x6f, 0x0a, 0x11, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f,
	0x70, 0x42, 0x75, 0x79, 0x53, 0x32, 0x43, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x70, 0x6c, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x70, 0x6c, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x22, 0x5a, 0x0a, 0x18, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x47, 0x65,
	0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x43, 0x32, 0x53, 0x12,
	0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22,
	0x5a, 0x0a, 0x18, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x47, 0x65, 0x74, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x53, 0x32, 0x43, 0x12, 0x1e, 0x0a, 0x0a, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x42, 0x0b, 0x5a, 0x09, 0x2e,
	0x3b, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_generate_operate_proto_rawDescOnce sync.Once
	file_generate_operate_proto_rawDescData = file_generate_operate_proto_rawDesc
)

func file_generate_operate_proto_rawDescGZIP() []byte {
	file_generate_operate_proto_rawDescOnce.Do(func() {
		file_generate_operate_proto_rawDescData = protoimpl.X.CompressGZIP(file_generate_operate_proto_rawDescData)
	})
	return file_generate_operate_proto_rawDescData
}

var file_generate_operate_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_generate_operate_proto_goTypes = []interface{}{
	(*OperateGetListC2S)(nil),        // 0: Game.OperateGetListC2S
	(*OperateGetListS2C)(nil),        // 1: Game.OperateGetListS2C
	(*OperateNewS2C)(nil),            // 2: Game.OperateNewS2C
	(*OperateUpdateS2C)(nil),         // 3: Game.OperateUpdateS2C
	(*OperateDeleteS2C)(nil),         // 4: Game.OperateDeleteS2C
	(*OperateGetTaskRewardC2S)(nil),  // 5: Game.OperateGetTaskRewardC2S
	(*OperateGetTaskRewardS2C)(nil),  // 6: Game.OperateGetTaskRewardS2C
	(*OperateSignC2S)(nil),           // 7: Game.OperateSignC2S
	(*OperateSignS2C)(nil),           // 8: Game.OperateSignS2C
	(*OperateRepairSignC2S)(nil),     // 9: Game.OperateRepairSignC2S
	(*OperateRepairSignS2C)(nil),     // 10: Game.OperateRepairSignS2C
	(*OperateShopBuyC2S)(nil),        // 11: Game.OperateShopBuyC2S
	(*OperateShopBuyS2C)(nil),        // 12: Game.OperateShopBuyS2C
	(*OperateGetScoreRewardC2S)(nil), // 13: Game.OperateGetScoreRewardC2S
	(*OperateGetScoreRewardS2C)(nil), // 14: Game.OperateGetScoreRewardS2C
	(*Operate)(nil),                  // 15: Game.Operate
	(*OperateActivityDB)(nil),        // 16: Game.OperateActivityDB
}
var file_generate_operate_proto_depIdxs = []int32{
	15, // 0: Game.OperateGetListS2C.list:type_name -> Game.Operate
	15, // 1: Game.OperateNewS2C.list:type_name -> Game.Operate
	16, // 2: Game.OperateUpdateS2C.detailed:type_name -> Game.OperateActivityDB
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_generate_operate_proto_init() }
func file_generate_operate_proto_init() {
	if File_generate_operate_proto != nil {
		return
	}
	file_global_operate_activity_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_generate_operate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateGetListC2S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_generate_operate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateGetListS2C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_generate_operate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateNewS2C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_generate_operate_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateUpdateS2C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_generate_operate_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateDeleteS2C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_generate_operate_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateGetTaskRewardC2S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_generate_operate_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateGetTaskRewardS2C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_generate_operate_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateSignC2S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_generate_operate_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateSignS2C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_generate_operate_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateRepairSignC2S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_generate_operate_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateRepairSignS2C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_generate_operate_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateShopBuyC2S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_generate_operate_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateShopBuyS2C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_generate_operate_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateGetScoreRewardC2S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_generate_operate_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateGetScoreRewardS2C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_generate_operate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_generate_operate_proto_goTypes,
		DependencyIndexes: file_generate_operate_proto_depIdxs,
		MessageInfos:      file_generate_operate_proto_msgTypes,
	}.Build()
	File_generate_operate_proto = out.File
	file_generate_operate_proto_rawDesc = nil
	file_generate_operate_proto_goTypes = nil
	file_generate_operate_proto_depIdxs = nil
}
